# Generated by Django 3.1 on 2020-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.TextField(default='test_field')),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('scoring_format', models.CharField(choices=[('STND', 'standard'), ('FPPR', 'ppr'), ('HPPR', 'half_ppr')], default='STND', max_length=4)),
                ('position', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('K', 'K')], default='QB', max_length=4)),
            ],
        ),
    ]
