# Generated by Django 2.2.9 on 2020-07-30 17:02

from django.db import migrations, models
import tiers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_path', models.FilePathField(path=tiers.models.plots_path)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('scoring_format', models.CharField(choices=[('STND', 'standard'), ('FPPR', 'ppr'), ('HPPR', 'half_ppr')], default='STND', max_length=4)),
                ('positon', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('K', 'K')], default='QB', max_length=2)),
            ],
        ),
    ]
